#!/bin/bash
# setting
#
ETC_DIR=$(cd $(dirname $0);pwd)
SCRIPT_DIR="$ETC_DIR/../scripts"

mouse_up() {
    $SCRIPT_DIR/tab_new.scpt
}

dammy() {
}

if [[ "$SHELL" =~ "zsh" ]]
then
    zle -N mouse_up
    zle -N dammy
    bindkey "^[\e[A" mouse_up
    # Esc + Up Key
fi

activate() {
    if [[ "$PS1" =~ "\(chrome\)*" ]]
    then
        echo "already activate chrome mode."
    else
        export PS1="(chrome)"$PS1
    fi
}

activate

deactivate() {
    if [[ "$PS1" =~ "\(chrome\)*" ]]
    then
        PS1=`echo $PS1 | sed -e "s/(chrome)//"`
        export PS1="(chrome)"$PS1
        source "$ETC_DIR/deactivate"
    else
        echo "not active chrome mode."
    fi
}
