#!/bin/bash
#
ETC_DIR=$(cd $(dirname ${BASH_SOURCE:-$0});pwd)
SCRIPT_DIR="$ETC_DIR/../scripts"

_mouse_up() {
    chrome_shell mouse u
    source "$ETC_DIR/keybind"
    _activate_mouse_mode
}

_mouse_down() {
    chrome_shell mouse d
    source "$ETC_DIR/keybind"
    _activate_mouse_mode
}

_mouse_right() {
    chrome_shell mouse r
    source "$ETC_DIR/keybind"
    _activate_mouse_mode
}

_mouse_left() {
    chrome_shell mouse l
    source "$ETC_DIR/keybind"
    _activate_mouse_mode
}

dammy() {
    echo >/dev/null 2>&1
}

if [[ "$SHELL" =~ "zsh" ]]
then
    zle -N _mouse_up
    zle -N _mouse_down
    zle -N _mouse_right
    zle -N _mouse_left
    zle -N dammy
    bindkey "^[\e[A" _mouse_up
    bindkey "^[\e[B" _mouse_down
    bindkey "^[\e[C" _mouse_right
    bindkey "^[\e[D" _mouse_left
    # Esc + Up Key
else
    bind '"\M-\e[A":_mouse_up'
    bind '"\M-\e[B":_mouse_down'
    bind '"\M-\e[C":_mouse_right'
    bind '"\M-\e[D":_mouse_left'
    # Esc + Up Key
fi


activate() {
    if [[ "$PS1" =~ "(chrome)" ]]
    then
        echo "already activate chrome mode."
    else
        echo "activate chrome mode."
        echo "if you want to deactivate, you execute \`deactivate\` command."
        export PS1="(chrome)"$PS1
    fi
}

activate

deactivate() {
    if [[ "$PS1" =~ "(chrome)" ]]
    then
        PS1=`echo $PS1 | sed -e "s/(chrome)//"`
        export PS1="(chrome)"$PS1
        source "$ETC_DIR/deactivate"
    else
        echo "not active chrome mode."
    fi
}

click() {
    chrome_shell click "$@"
}

mouse() {
    chrome_shell mouse "$@"
}

wmove() {
    chrome_shell wmove "$@"
}

scroll() {
    chrome_shell scroll "$@"
}

wsize() {
    chrome_shell wsize "$@"
}

tab() {
    chrome_shell tab "$@"
}

back() {
    chrome_shell back "$@"
}

next() {
    chrome_shell next "$@"
}

reload() {
    chrome_shell reload "$@"
}

abort() {
    chrome_shell abort "$@"
}

home() {
    chrome_shell home "$@"
}

start() {
    chrome_shell start "$@"
}

restart() {
    chrome_shell restart "$@"
}

stop() {
    chrome_shell stop "$@"
}

wopen() {
    chrome_shell wopen "$@"
}

wclose() {
    chrome_shell wclose "$@"
}

search() {
    chrome_shell search "$@"
}

url() {
    chrome_shell url "$@"
}

typo() {
    chrome_shell typo "$@"
}
