ETC_DIR=$(cd $(dirname $0);pwd)
BIN_DIR="$ETC_DIR/../bin"
SCRIPT_DIR="$ETC_DIR/../scripts"

PY_CHROME_SHELL="$BIN_DIR/chrome_shell.py"

chrome_shell() {
    if [ $# -le 2 ]
    then
        if [ "$1" = "activate" ]
        then
            source "$ETC_DIR/activate"
            return 1
        fi
    fi
    $PY_CHROME_SHELL "$@"
}

chrome(){
    chrome_shell "$@"
}
